# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('token', models.CharField(default=b'00000000000000000000000000000000', editable=False, max_length=32)),
            ],
        ),
    ]
